### ISSUE TITLE
The program cannot find the phone.

### ISSUE THREAD

**Issue by sweetlanzi** [ju1ce/Mediapipe-VR-Fullbody-Tracking#16]
The program cannot find the phone. I have set my computer and my phone on the same wifi, but no matter how I change the IP, the program cannot take effect.

Importing libraries....
Reading parameters...
Save file not found, will be created after you exit the program.
Opening camera...
Connecting to SteamVR
Error in SteamVR connection. Retrying...
Starting pose detector...
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
[tcp @ 0000018fff298f40] Connection to tcp://192.168.1.20:8080 failed: Error number -138 occurred
[ERROR:0@408.395] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap.cpp (166) cv::VideoCapture::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): http://192.168.1.20:8080/video in function 'cv::icvExtractPattern'

Camera opened!
Exception in thread Thread-2 (camera_thread_fun):
Traceback (most recent call last):
  File "threading.py", line 1009, in _bootstrap_inner
  File "threading.py", line 946, in run
  File "mediapipepose.py", line 67, in camera_thread_fun
AssertionError: Camera capture failed! Check the cameraid parameter.
Traceback (most recent call last):
  File "mediapipepose.py", line 185, in <module>
AttributeError: 'NoneType' object has no attribute 'copy'
[21700] Failed to execute script 'mediapipepose' due to unhandled exception!

**Comment by u-Kotovsky** [comment]
Is phone has running camera server such as DroidCam? Did you put server ip and port in it?

**Comment by sweetlanzi** [comment]
> Is phone has running camera server such as DroidCam? Did you put server ip and port in it?

I have solved the problem, thank you

**Comment by lunchanddinner** [comment]
> > Is phone has running camera server such as DroidCam? Did you put server ip and port in it?
> 
> I have solved the problem, thank you

Sorry to ask, how did you solve your problem?

**Comment by miladint-dot** [comment]
> > Is phone has running camera server such as DroidCam? Did you put server ip and port in it?
> 
> I have solved the problem, thank you

hey do you remember what was the solution to your problem? I'm having same issue right now
