### ISSUE TITLE
I have a trouble  in installation activateMultipleDrivers 

### ISSUE THREAD

**Issue by 872858554** [ju1ce/Mediapipe-VR-Fullbody-Tracking#19]
Steam directory found. (C:/Program Files (x86)/Steam)
SteamVR directory located. (C:/Program Files (x86)/Steam/steamapps/common/SteamVR)
Traceback (most recent call last):
  File "installer.py", line 60, in <module>
  File "json\__init__.py", line 293, in load
UnicodeDecodeError: 'gbk' codec can't decode byte 0xac in position 959: illegal multibyte sequence
[11200] Failed to execute script installer

[已退出进程，代码为 4294967295 (0xffffffff)]

**Comment by ju1ce** [comment]
That is weird, im guessing its an issue with a different language... You may need to install the driver manualy. Copied from the ApriltagTrackers wiki:

Inside the driver_files folder, there is a apriltagtrackers folder. Copy this folder to "Steam/steamapps/common/SteamVR/drivers". Now, open "Steam/config/steamvr.vrsettings" and, under "steamvr", add the field "activateMultipleDrivers" : true, . The section will now look something like:
```
"steamvr" : {
      "activateMultipleDrivers" : true,
      "installID" : "17046041383408253036",
      "lastVersionNotice" : "1.15.10",
      "lastVersionNoticeDate" : "1605567489",
      "showAdvancedSettings" : true
   },
```
