### ISSUE TITLE
Incorrect camera id

### ISSUE THREAD

**Issue by CassieCatYT** [ju1ce/Mediapipe-VR-Fullbody-Tracking#20]
When I run it it says this:
Importing libraries....
Reading parameters...
Save file not found, will be created after you exit the program.
Opening camera...
Connecting to SteamVR
Camera opened!
Exception in thread Thread-2 (camera_thread_fun):
Traceback (most recent call last):
  File "threading.py", line 1009, in _bootstrap_inner
  File "threading.py", line 946, in run
  File "mediapipepose.py", line 67, in camera_thread_fun
AssertionError: Camera capture failed! Check the cameraid parameter.
Starting pose detector...
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Traceback (most recent call last):
  File "mediapipepose.py", line 185, in <module>
AttributeError: 'NoneType' object has no attribute 'copy'
[24024] Failed to execute script 'mediapipepose' due to unhandled exception!
Press any key to continue . . .

I have tried to change the camera id to practically everything in device manager and it does not work
Please Help!

**Comment by CassieCatYT** [comment]
Turns out I didnt read the README file, so if you have this problem, just read the darn file
