### ISSUE TITLE
Mediapipepose error

### ISSUE THREAD

**Issue by Alerakk** [ju1ce/Mediapipe-VR-Fullbody-Tracking#36]
I tried beta 0,7 and 0.6 version.
I installed and uninstalled the drivers.
I checked addons in steamvr.
I tried cam id's between 0-2 some 0 and 1 had no problem.
I only tried with steamvr but it doesn't matter bec in 0.6 it doesn't ask which app
How can I solve this?
![Mediapipe Pose Error](https://github.com/ju1ce/Mediapipe-VR-Fullbody-Tracking/assets/93790037/fb311de5-381b-48b8-b3ff-4368b9732881)

Traceback (most recent call last):
  File "mediapipepose.py", line 181, in <module>
  File "mediapipepose.py", line 60, in main
  File "mediapipe\python\solutions\pose.py", line 146, in __init__
  File "mediapipe\python\solution_base.py", line 264, in __init__
FileNotFoundError: The path does not exist.
[15656] Failed to execute script 'mediapipepose' due to unhandled exception!
Press any key to continue . . .

**Comment by ju1ce** [comment]
The most common cause of this issue is not unzipping the files. Make sure that you extract all of the files in the zip into a folder somewhere on your pc, and only then run the program.

Similar issues can sometimes also happen if the program is in a place it doesnt have write permissions, but i dont think that is the issue here.

**Comment by Alerakk** [comment]
I had to format my pc for some problems. When I did, this fixed too. I just readed the whole page about the software. I understanded many things, First thing in the morning, I am going to fix some of my problems like not being on the ground and not calibrating properly.
Do you know any games to use this software? I used on VRchat and Blade and Sorcery(doesn't calibrate properly)

**Comment by ju1ce** [comment]
personaly, i just use it for social apps. I dont think its really accurate enough to be kicking stuff with it...

What calibration problems do you have? Make sure to stand straight, look straight ahead and hit the recalibrate button every time you start the program, and it will automaticaly calibrate the trackers to the correct positions. In vrchat, you can enter the vrchat t-pose fbt calibration thing, and see exactly how well the tracking balls align with your body.

Some possible issues:
- The balls are way too high/too low: scale calibration can sometimes fail, just adjust the scale slider manualy untill the balls are just above the ground
- The movement is mirrored: usualy means that the camera is mirrored, just check the "mirror camera" parameter and recalibrate
- The balls dont line up properly: use the rotation sliders to adjust everything manualy, until the balls are just inside your ankles. Note that the positions will be a bit different based on your overall pose, so try to get it as best as you can in a pose you are most likely to be in
