### ISSUE TITLE
issue with conecting my phone camera

### ISSUE THREAD

**Issue by miladint-dot** [ju1ce/Mediapipe-VR-Fullbody-Tracking#52]
Importing libraries....
Reading parameters...
Save file not found, will be created after you exit the program.
Opening camera...
Connecting to SteamVR
Starting pose detector...
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
[ERROR:0@25.529] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap.cpp (166) cv::VideoCapture::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): http://192.168.0.101:8080/video in function 'cv::icvExtractPattern'

Camera opened!
Exception in thread Thread-2 (camera_thread_fun):
Traceback (most recent call last):
  File "threading.py", line 1009, in _bootstrap_inner
  File "threading.py", line 946, in run
  File "mediapipepose.py", line 67, in camera_thread_fun
AssertionError: Camera capture failed! Check the cameraid parameter.
Traceback (most recent call last):
  File "mediapipepose.py", line 185, in <module>
AttributeError: 'NoneType' object has no attribute 'copy'
[12204] Failed to execute script 'mediapipepose' due to unhandled exception!
Press any key to continue . . .

**Comment by miladint-dot** [comment]
I have resolved this issue by doing 2 things different than before I used steam link instead of the regular airlink to connect to my desktop and a second thing which I probably shouldn't even mention cuz there is no way it was that was getting the IP webcam pro (the paid version) but really there is no way it was because of this.
